---
- hosts: 172.31.31.250
  become: yes
  tasks:
  - include_tasks: file.yml
  - name: i want to install webserver
    apt:
     name: apache2
     state: present
  - name: i want to copy file into ansible nodes
    template:
     src: indexfile.j2
     dest: /var/www/html/index.html
    
  


