---
- hosts: 172.31.20.140
  become: yes
  tasks:
  - include_tasks: file.yml
  - name: i want to install webserver
    apt:
     name: apache2
     state: present
    notify: restart webserver 
  - name: i want to copy file into ansible nodes
    template:
     src: indexfile.j2
     dest: /var/www/html/index.html
    notify: restart webserver

  handlers:    
  - name: restart webserver
    service:
     name: apache2
     state: restarted

    
  


