---
- hosts: webservers
  become: yes
  tasks:
  - name:  install java on   ubuntu ansible nodes
    apt:
     name: "{{javapackforubuntu}}"
     state: present
    when: ansible_os_family =="Debian"

  - name:  install java on  RedHat ansible nodes  
    yum:
     name: "{{javapackforredhat}}"
     state: present
    when: ansible_os_family =="RedHat"  

