---
- hosts: webservers
  become: yes
  tasks:
  - name: i want to install java on ubuntu ansible nodes
    apt:
     name: "{{javapackforubuntu}}"
     state: present
    when: ansible_os_family =="Debian" 
   
  - name: i want to install java on redhat ansible nodes
    yum:
     name: "{{javapackforredhat}}"
     state: present
    when: ansible_os_family =="RedHat" 
  