---
- name: copy tomcat user file into nodeside
  template:
   src: templates/tomuser.j2
   dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy tomcat context file into nodeside
  template:
    src: templates/tomcontext.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy tomcat host context file into nodeside
  template:
   src: templates/tomhostcontext.j2
   dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml