---
- name: install jenkins
  get_url:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -th/file.conf
    dest: home/ubuntu/jenkins
    force_basic_auth: yes

- name: add jenkins key
  ansible.builtin.apt_repository:
    repo: wget -qO - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -
    state: present

- name: "Set EPEL yum repository"
  apt_repository:
      filename: "{{ item.value.name }}"
      repo: "{{ item.value.url }}"
      description: "{{ item.value.description }}"
- name: i want to install jenkins on ubuntu 
  apt:
     name: "{{jenkinsforubuntu}}"
     state: present
     when: ansible_os_family =="Debian" 
     
          