---
- name: install jenkins
  get_url:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -th/file.conf
    dest: home/ubuntu/jenkins
    force_basic_auth: yes

- name: append the Debian package repository    
  command:
       cmd: https://pkg.jenkins.io/debian-stable binary/ 
       creates: /etc/apt/sources.list.d

- name: i want to install jenkins on ubuntu 
  apt:
     name: "{{jenkinsforubuntu}}"
     state: present
     when: ansible_os_family =="Debian" 
     
          