---

- name: Update repositories cache and install "jenkins" package
  apt:
    name: jenkins
    update_cache: yes

- name: start jenkins
  systemd:
    name: jenkins
    state: started
    daemon_reload: yes
    enabled: yes

