---
- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: jenkins


- name: ensure jenkins is running
  service: 
    name: jenkins
    enabled: true
    state: started