---
# tasks file for webrole
- name: install webserver
  apt:
   name: apache2
   state: present

- name: copy index file
  template:
   src: indexfile.j2
   dest: /var/www/html/index.html
   notify: restart webserver