---
# tasks file for webrole
- name: install webserver
  apt:
   name: apache2
   state: present

- name: copy indexfile
  template:
    src: templates/indexfile.j2
    dest: /var/www/html/index.html
  notify: restart webserver